CrudDapperMvc/Models/Pessoas.cs
namespace CrudDapperMvc.Models
{
    public class Pessoas
    {
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public float Peso { get; set; }

        public Pessoas() { }
    }
}

CrudDapperMvc/Controllers/PessoasController.cs
using CrudDapperMvc.Models;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace CrudDapperMvc.Controllers
{
    public class PessoasController : Controller
    {
        private readonly string connectionsString = "Server=DESKTOP-O1775Q7;Database=PessoasDb;User Id=sa;Password=123456;Trusted_Connection=True;TrustServerCertificate=True;";


        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Pessoas> listaPessoas;
            IDbConnection con;

            try
            {
                string query = "SELECT * FROM Pessoas";
                con = new SqlConnection(connectionsString);
                con.Open();
                listaPessoas = con.Query<Pessoas>(query).ToList();
                con.Close();
                return View(listaPessoas);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Pessoas pessoas)
        {
            if (ModelState.IsValid)
            {
                IDbConnection con;

                try
                {
                    string query = "INSERT INTO Pessoas(Nome, Idade, Peso) VALUES(@Nome, @Idade, @Peso)";
                    con = new SqlConnection(connectionsString);
                    con.Open();
                    con.Execute(query, pessoas);
                    con.Close();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }
            return View(pessoas);
        }

        [HttpGet]
        public IActionResult Edit(int pessoaId)
        {
            if (pessoaId == null) return NotFound();
            IDbConnection con;

            try
            {
                string query = "SELECT * FROM pessoas WHERE PessoaId = @pessoaId";
                con = new SqlConnection(connectionsString);
                con.Open();
                Pessoas pessoas = con.Query<Pessoas>(query, new { pessoaId = pessoaId}).FirstOrDefault();
                con.Close();
                return View(pessoas);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public IActionResult Edit(int pessoaId, Pessoas pessoas)
        {
            if (pessoaId != pessoas.PessoaId) return NotFound();

            if (ModelState.IsValid)
            {
                IDbConnection con;

                try
                {
                    con = new SqlConnection(connectionsString);
                    string queryAtualizada = "UPDATE pessoas SET Nome=@Nome, Idade=@Idade, Peso=@Peso WHERE PessoaId=@pessoaId";
                    con.Open();
                    con.Execute(queryAtualizada, pessoas);
                    con.Close();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    throw ex;
                }
            }
            return View(pessoas);
        }

        [HttpPost]
        public IActionResult Delete(int pessoaId)
        {
                IDbConnection con;

                try
                {
                    con = new SqlConnection(connectionsString);
                    string query = "DELETE FROM pessoas WHERE PessoaId=@pessoaId";
                    con.Open();
                    con.Execute(query, new {pessoaId = pessoaId});
                    con.Close();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {

                    throw ex;
                }
        }
    }
}

CrudDapperMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudDapperMvc/Views/Pessoas/Create.cshtml
@model CrudDapperMvc.Models.Pessoas

@{
    ViewData["Title"] = "Nova pessoa";
}



<h4 class="alert alert-secondary">Nova pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" />&emsp;
                <a class="btn btn-danger btn-sm" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

CrudDapperMvc/Views/Pessoas/Edit.cshtml
@model CrudDapperMvc.Models.Pessoas

@{
    ViewData["Title"] = "Atualizar" + Model.Nome;
}


<h4 class="alert alert-secondary">Atualizar @Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="PessoaId" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-outline-primary btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-outline-danger btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

CrudDapperMvc/Views/Pessoas/Index.cshtml
@model IEnumerable<CrudDapperMvc.Models.Pessoas>

@{
    ViewData["Title"] = "Listagem de pessoas";
}

<h4>Listagem de pessoas</h4>

<p>
    <a asp-action="Create" asp-controller="Pessoas" class="btn btn-outline-success btn-sm">Nova pessoas</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Peso)
                </td>
                <td>
                    <div class="d-flex">
                        <a asp-controller="Pessoas" asp-action="Edit" asp-route-pessoaId="@item.PessoaId" class="btn btn-outline-info btn-sm mr-2">Atualizar</a>
                        <form asp-controller="Pessoas" asp-action="Delete" asp-route-pessoaId="@item.PessoaId" onsubmit="return confirm('Prosseguir com a exclusão do usuário @item.Nome?');" class="d-inline">
                            <button type="submit" class="btn btn-outline-danger btn-sm">Excluir</button>
                        </form>
                    </div>
                </td>


            </tr>
        }
    </tbody>
</table>

CrudDapperMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudDapperMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pessoas" asp-action="Index">CrudDapperMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CrudDapperMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>